CREATE TABLE [TB_CATEGORIE] (
  [I_COD_CATEGORIE] INT PRIMARY KEY IDENTITY(1, 1),
  [S_NM_CATEGORIE] VARCHAR(100) NOT NULL,
  [S_SLUG_CATEGORIE] VARCHAR(100) NOT NULL,
  [B_ISACTIVE_CATEGORIE] BIT NOT NULL DEFAULT 1,
  CONSTRAINT [UQ_SLUG_CATEGORIE] UNIQUE ([S_SLUG_CATEGORIE])
)
GO

CREATE TABLE [TB_USER] (
  [I_COD_USER] INT PRIMARY KEY IDENTITY(1, 1),
  [S_MAIL_USER] VARCHAR(255) NOT NULL,
  [S_PASSWORD_USER] VARCHAR(255) NOT NULL,
  [S_FIRSTNAME_USER] VARCHAR(100) NOT NULL,
  [S_LASTNAME_USER] VARCHAR(100) NOT NULL,
  [I_ROLE_USER] INT NOT NULL, -- criar uma tabela de domínios para isso ou CHECK CONSTRAINT
  [DT_CREATEAT_USER] DATETIME NOT NULL DEFAULT GETDATE(),
  [B_ISACTVE_USER] BIT NOT NULL DEFAULT 1,
  CONSTRAINT [UQ_MAIL_USER] UNIQUE ([S_MAIL_USER])
)
GO

CREATE TABLE [TB_PRODUCTTEMPLATE] (
  [I_COD_PRODUCTTEMPLATE] INT PRIMARY KEY IDENTITY(1, 1),
  [I_COD_CATEGORIE] INT NOT NULL,
  [S_NAME_PRODUCTTEMPLATE] VARCHAR(200) NOT NULL,
  [S_DESCRIPTION_PRODUCTTEMPLATE] VARCHAR(MAX) NOT NULL,
  [S_SLUG_PRODUCTTEMPLATE] VARCHAR(255) NOT NULL,
  [B_ISACTIVE_PRODUCTTEMPLATE] BIT NOT NULL DEFAULT 1,
  CONSTRAINT [UQ_SLUG_PRODUCTTEMPLATE] UNIQUE ([S_SLUG_PRODUCTTEMPLATE]),
  CONSTRAINT [FK_PRODUCTTEMPLATE_CATEGORIE] FOREIGN KEY ([I_COD_CATEGORIE]) REFERENCES [TB_CATEGORIE] ([I_COD_CATEGORIE])
)
GO

CREATE TABLE [TB_PRODUCTVARIANT] (
  [I_COD_PRODUCTVARIANT] INT PRIMARY KEY IDENTITY(1, 1),
  [I_COD_PRODUCTTEMPLATE] INT NOT NULL,
  [S_SKU_PRODUCTVARIANT] VARCHAR(50) NOT NULL,
  [D_PRICE_PRODUCTVARIANT] DECIMAL(18,2) NOT NULL,
  [D_COSTPRICE_PRODUCTVARIANT] DECIMAL(18,2) NOT NULL,
  [I_STOCK_PRODUCTVARIANT] INT NOT NULL DEFAULT 0,
  [J_ATRIBUTES_PRODUCTVARIANT] NVARCHAR(MAX) NOT NULL, -- JSON armazenado como texto
  [TS_ROWVERSION_PRODUCTVARIANT] ROWVERSION NOT NULL, 
  CONSTRAINT [UQ_SKU_PRODUCTVARIANT] UNIQUE ([S_SKU_PRODUCTVARIANT]),
  CONSTRAINT [FK_PRODUCTVARIANT_TEMPLATE] FOREIGN KEY ([I_COD_PRODUCTTEMPLATE]) REFERENCES [TB_PRODUCTTEMPLATE] ([I_COD_PRODUCTTEMPLATE])
)
GO

CREATE TABLE [TB_PRODUCTIMAGE] (
  [I_COD_PRODUCTIMAGE] INT PRIMARY KEY IDENTITY(1, 1),
  [I_COD_PRODUCTTEMPLATE] INT NOT NULL,
  [I_COD_PRODUCTVARIANT] INT NULL, -- Pode ser nulo se a imagem for geral do template
  [S_URL_PRODUCTIMAGE] VARCHAR(255) NOT NULL,
  [B_ISMAIN_PRODUCTIMAGE] BIT NOT NULL DEFAULT 0,
  [I_DISPLAYORDER_PRODUCTIMAGE] INT NOT NULL DEFAULT 0,
  CONSTRAINT [FK_PRODUCTIMAGE_TEMPLATE] FOREIGN KEY ([I_COD_PRODUCTTEMPLATE]) REFERENCES [TB_PRODUCTTEMPLATE] ([I_COD_PRODUCTTEMPLATE]),
  CONSTRAINT [FK_PRODUCTIMAGE_VARIANT] FOREIGN KEY ([I_COD_PRODUCTVARIANT]) REFERENCES [TB_PRODUCTVARIANT] ([I_COD_PRODUCTVARIANT])
)
GO

CREATE TABLE [TB_PRICEHISTORY] (
  [I_COD_PRICEHISTORY] INT PRIMARY KEY IDENTITY(1, 1),
  [I_COD_PRODUCTVARIANT] INT NOT NULL,
  [I_COD_USER] INT NOT NULL, -- Usuário que alterou
  [D_OLDPRICE_PRICEHISTORY] DECIMAL(18,2) NOT NULL,
  [D_NEWPRICE_PRICEHISTORY] DECIMAL(18,2) NOT NULL,
  [D_OLDCOST_PRICEHISTORY] DECIMAL(18,2) NOT NULL,
  [D_NEWCOST_PRICEHISTORY] DECIMAL(18,2) NOT NULL,
  [DT_CHANGEDATE_PRICEHISTORY] DATETIME NOT NULL DEFAULT GETDATE(),
  CONSTRAINT [FK_PRICEHISTORY_VARIANT] FOREIGN KEY ([I_COD_PRODUCTVARIANT]) REFERENCES [TB_PRODUCTVARIANT] ([I_COD_PRODUCTVARIANT]),
  CONSTRAINT [FK_PRICEHISTORY_USER] FOREIGN KEY ([I_COD_USER]) REFERENCES [TB_USER] ([I_COD_USER])
)
GO

CREATE TABLE [TB_PROMOTION] (
  [I_COD_PROMOTION] INT PRIMARY KEY IDENTITY(1, 1),
  [S_NAME_PROMOTION] VARCHAR(100) NOT NULL,
  [S_USECODE_PROMOTION] VARCHAR(50) NULL,
  [S_DISCOUNTTYPE_PROMOTION] VARCHAR(20) NOT NULL, -- Enum simulado
  [D_VALUE_PROMOTION] DECIMAL(18,2) NOT NULL,
  [DT_STARTDATE_PROMOTION] DATETIME NOT NULL,
  [DT_ENDDATE_PROMOTION] DATETIME NOT NULL,
  [B_ISACTIVE_PROMOTION] BIT NOT NULL DEFAULT 1,
  CONSTRAINT [UQ_USECODE_PROMOTION] UNIQUE ([S_USECODE_PROMOTION]),
  CONSTRAINT [CK_DISCOUNTTYPE] CHECK ([S_DISCOUNTTYPE_PROMOTION] IN ('percentage', 'fixedAmount'))
)
GO

CREATE TABLE [TB_PROMOTIONSITEM] (
  [I_COD_PROMOTIONSITEM] INT PRIMARY KEY IDENTITY(1, 1),
  [I_COD_PROMOTION] INT NOT NULL,
  [I_COD_PRODUCTVARIANT] INT NULL,
  [I_COD_CATEGORIE] INT NULL, -- deve permitir nulo caso seja promoção por variante
  CONSTRAINT [FK_PROMOTIONSITEM_PROMOTION] FOREIGN KEY ([I_COD_PROMOTION]) REFERENCES [TB_PROMOTION] ([I_COD_PROMOTION]),
  CONSTRAINT [FK_PROMOTIONSITEM_VARIANT] FOREIGN KEY ([I_COD_PRODUCTVARIANT]) REFERENCES [TB_PRODUCTVARIANT] ([I_COD_PRODUCTVARIANT]),
  CONSTRAINT [FK_PROMOTIONSITEM_CATEGORIE] FOREIGN KEY ([I_COD_CATEGORIE]) REFERENCES [TB_CATEGORIE] ([I_COD_CATEGORIE])
)
GO

CREATE TABLE [TB_ORDER] (
  [I_COD_ORDER] INT PRIMARY KEY IDENTITY(1, 1),
  [I_COD_USER] INT NOT NULL,
  [DT_ORDERDT_ORDER] DATETIME NOT NULL DEFAULT GETDATE(), 
  [D_TOTALAMOUNT_ORDER] DECIMAL(18,2) NOT NULL,
  [D_DISCOUNTAMOUNT_ORDER] DECIMAL(18,2) NOT NULL, 
  [D_NETAMOUNT_ORDER] DECIMAL(18,2) NOT NULL,
  [S_STATUS_ORDER] VARCHAR(20) NOT NULL, -- Enum simulado
  [S_SHIPSSTREET_ORDER] VARCHAR(255) NOT NULL,
  [S_SHIPNUMBER_ORDER] VARCHAR(20) NOT NULL,
  [S_SHIPZIPCODE_ORDER] VARCHAR(20) NOT NULL,
  [S_SHIPCITY_ORDER] VARCHAR(100) NOT NULL,
  [S_SHIPSTATE_ORDER] VARCHAR(2) NOT NULL,
  CONSTRAINT [FK_ORDER_USER] FOREIGN KEY ([I_COD_USER]) REFERENCES [TB_USER] ([I_COD_USER]),
  CONSTRAINT [CK_STATUS_ORDER] CHECK ([S_STATUS_ORDER] IN ('Pending', 'Paid', 'Shipped', 'Delivered', 'Canceled'))
)
GO

CREATE TABLE [TB_ORDERITEM] (
  [I_COD_ORDERITEM] INT PRIMARY KEY IDENTITY(1, 1),
  [I_COD_ORDER] INT NOT NULL,
  [I_COD_PRODUCTVARIANT] INT NOT NULL,
  [S_SNAPSHOTNAME_ORDERITEM] VARCHAR(255) NOT NULL,
  [I_QUANTITY_ORDERITEM] INT NOT NULL,
  [D_UNITPRICE_ORDERITEM] DECIMAL(18,2) NOT NULL,
  [D_UNITCOST_ORDERITEM] DECIMAL(18,2) NOT NULL,
  CONSTRAINT [FK_ORDERITEM_ORDER] FOREIGN KEY ([I_COD_ORDER]) REFERENCES [TB_ORDER] ([I_COD_ORDER]),
  CONSTRAINT [FK_ORDERITEM_VARIANT] FOREIGN KEY ([I_COD_PRODUCTVARIANT]) REFERENCES [TB_PRODUCTVARIANT] ([I_COD_PRODUCTVARIANT])
)
GO

CREATE TABLE [TB_ORDERPROMOTION] (
  [I_COD_ORDERPROMOTION] INT PRIMARY KEY IDENTITY(1, 1),
  [I_COD_ORDER] INT NOT NULL,
  [I_COD_PROMOTION] INT NOT NULL,
  [S_SNAPSHOTPROMOTIONNAME_ORDERPROMOTION] VARCHAR(100) NOT NULL,
  [D_DISCOUNTAPLLYED_ORDERPROMOTION] DECIMAL(18,2) NOT NULL,
  CONSTRAINT [FK_ORDERPROMOTION_ORDER] FOREIGN KEY ([I_COD_ORDER]) REFERENCES [TB_ORDER] ([I_COD_ORDER]),
  CONSTRAINT [FK_ORDERPROMOTION_PROMOTION] FOREIGN KEY ([I_COD_PROMOTION]) REFERENCES [TB_PROMOTION] ([I_COD_PROMOTION])
)
GO

CREATE TABLE [TB_PAYMENT] (
  [I_COD_PAYMENT] INT PRIMARY KEY IDENTITY(1, 1),
  [I_COD_ORDER] INT NOT NULL,
  [S_GATEWAYID_PAYMENT] VARCHAR(100) NULL,
  [S_METHOD_PAYMENT] VARCHAR(20) NOT NULL,
  [S_STATUS_PAYMENT] VARCHAR(20) NOT NULL,
  [D_AMOUNT_PAYMENT] DECIMAL(18,2) NOT NULL,
  [DT_CREATEAT_PAYMENT] DATETIME NOT NULL DEFAULT GETDATE(),
  CONSTRAINT [FK_PAYMENT_ORDER] FOREIGN KEY ([I_COD_ORDER]) REFERENCES [TB_ORDER] ([I_COD_ORDER]),
  CONSTRAINT [CK_METHOD_PAYMENT] CHECK ([S_METHOD_PAYMENT] IN ('CreditCard', 'Pix', 'Boleto')),
  CONSTRAINT [CK_STATUS_PAYMENT] CHECK ([S_STATUS_PAYMENT] IN ('Processing', 'Approved', 'Failed', 'Refunded'))
)
GO

CREATE TABLE [TB_STOCKMOVEMENT] (
  [I_COD_STOCKMOVEMENT] INT PRIMARY KEY IDENTITY(1, 1),
  [I_COD_PRODUCTVARIANT] INT NOT NULL,
  [I_COD_ORDER] INT NULL, -- Pode ser NULL se for um ajuste manual sem pedido
  [I_QUANTITY_STOCKMOVEMENT] INT NOT NULL,
  [S_MOVETYPE_STOCKMOVEMENT] VARCHAR(20) NOT NULL,
  [D_VALUEATTIME_STOCKMOVEMENT] DECIMAL(18,2) NOT NULL,
  [DT_MOVEDATE_STOCKMOVEMENT] DATETIME NOT NULL DEFAULT GETDATE(),
  CONSTRAINT [FK_STOCKMOVEMENT_VARIANT] FOREIGN KEY ([I_COD_PRODUCTVARIANT]) REFERENCES [TB_PRODUCTVARIANT] ([I_COD_PRODUCTVARIANT]),
  CONSTRAINT [FK_STOCKMOVEMENT_ORDER] FOREIGN KEY ([I_COD_ORDER]) REFERENCES [TB_ORDER] ([I_COD_ORDER]),
  CONSTRAINT [CK_MOVETYPE_STOCKMOVEMENT] CHECK ([S_MOVETYPE_STOCKMOVEMENT] IN ('purchase', 'sale', 'adjustment', 'return'))
)
GO

CREATE TABLE [TB_CART] (
  [I_COD_CART] INT PRIMARY KEY IDENTITY(1, 1),
  [I_COD_USER] INT NOT NULL,
  [DT_CREATEAT_CART] DATETIME NOT NULL DEFAULT GETDATE(),
  [DT_EXPIREAT_CART] DATETIME NOT NULL,
  CONSTRAINT [UQ_USER_CART] UNIQUE ([I_COD_USER]),
  CONSTRAINT [FK_CART_USER] FOREIGN KEY ([I_COD_USER]) REFERENCES [TB_USER] ([I_COD_USER])
)
GO

CREATE TABLE [TB_CARTITEM] (
  [I_COD_CARTITEM] INT PRIMARY KEY IDENTITY(1, 1),
  [I_COD_CART] INT NOT NULL,
  [I_COD_PRODUCTVARIANT] INT NOT NULL,
  [I_QUANTITY_CARTITEM] INT NOT NULL,
  CONSTRAINT [FK_CARTITEM_CART] FOREIGN KEY ([I_COD_CART]) REFERENCES [TB_CART] ([I_COD_CART]),
  CONSTRAINT [FK_CARTITEM_VARIANT] FOREIGN KEY ([I_COD_PRODUCTVARIANT]) REFERENCES [TB_PRODUCTVARIANT] ([I_COD_PRODUCTVARIANT])
)
GO

CREATE TABLE [TB_PRODUCTREVIEW] (
  [I_COD_PRODUCTREVIEW] INT PRIMARY KEY IDENTITY(1, 1),
  [I_COD_PRODUCTTEMPLATE] INT NOT NULL,
  [I_COD_USER] INT NOT NULL,
  [I_COD_ORDER] INT NOT NULL,
  [I_RATING_PRODUCTREVIEW] INT NOT NULL,
  [S_TITLE_PRODUCTREVIEW] VARCHAR(100) NULL,
  [S_COMMENT_PRODUCTREVIEW] VARCHAR(MAX) NULL, 
  [DT_CREATEDAT_PRODUCTREVIEW] DATETIME NOT NULL DEFAULT GETDATE(),
  CONSTRAINT [FK_PRODUCTREVIEW_TEMPLATE] FOREIGN KEY ([I_COD_PRODUCTTEMPLATE]) REFERENCES [TB_PRODUCTTEMPLATE] ([I_COD_PRODUCTTEMPLATE]),
  CONSTRAINT [FK_PRODUCTREVIEW_USER] FOREIGN KEY ([I_COD_USER]) REFERENCES [TB_USER] ([I_COD_USER]),
  CONSTRAINT [FK_PRODUCTREVIEW_ORDER] FOREIGN KEY ([I_COD_ORDER]) REFERENCES [TB_ORDER] ([I_COD_ORDER]),
  CONSTRAINT [CK_RATING_PRODUCTREVIEW] CHECK ([I_RATING_PRODUCTREVIEW] BETWEEN 1 AND 5)
)
GO